name: gobabel_string_extractor
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.8.0

dependency_overrides: 
  lints: ^6.0.0
  test: ^1.26.2


# Add regular dependencies here.
dependencies:
  args: ^2.7.0
  crypto: ^3.0.6
  console_bars: ^1.2.0
  path: ^1.9.1        # for cross-platform path handling
  analyzer: ^7.4.5    # for parsing Dart code (AST)
  gobabel_client:
    path: ../go_babel_app/gobabel_client
  gobabel_core:
    path: ../gobabel_core
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.15
  freezed: ^2.5.8
  json_serializable: ^6.9.5
  lints: ^6.0.0
  test: ^1.26.2
